### ISSUE TITLE
Any equivalent of serverless events? (http hooks)

### ISSUE THREAD

**Issue by balupton** [apex/apex#643]
https://serverless.com/framework/docs/providers/aws/guide/events/

```
# 'functions' in serverless.yml
functions:
  createUser: # Function name
    handler: handler.users # Reference to file handler.js & exported function 'users'
    events: # All events associated with this function
      - http:
          path: users/create
          method: post
      - http:
          path: users/update
          method: put
      - http:
          path: users/delete
          method: delete
```

Would be good to be able to expose functions to HTTP urls
